# This is an exercise file for numpy

In [1]:
mylist = [1, 2, 3, 4]

In [2]:
import numpy as np

In [15]:
my1DArray = np.array(mylist)

In [16]:
my1DArray

array([1, 2, 3, 4])

In [12]:
my2DList = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]

In [13]:
my2DArray = np.array(my2DList)

In [14]:
my2DArray

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## To check if an array is 1D or 2D, check the number of brackets it begins and ends with. If it is 2, then it is a 2D array else it is a 1D array.

In [17]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.zeros(4)

array([0., 0., 0., 0.])

## Prints a 1D matrix (vector) of zeros

In [20]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Prints a 3x3 matrix of zeros